<a href="https://colab.research.google.com/github/Patel-Aman/data_science_basics/blob/main/comparison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries and training data

print('Importing Data and libraries...')
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

X = pd.read_csv('/content/drive/MyDrive/competion1/traindata - traindata.csv')
y = pd.read_csv('/content/drive/MyDrive/competion1/trainlabel - trainlabel.csv')
Xt = pd.read_csv('/content/drive/MyDrive/competion1/testdata - testdata.csv')
print('Done')

In [ ]:
#Convert data from string to list format into dataframe

dummy = list(X.features)
for i in range(len(dummy)):
    dummy[i] = list(map(float, dummy[i][1:-1].split(",")))

dum = list(Xt.features)
for i in range(len(dum)):
    dum[i] = list(map(float, dum[i][1:-1].split(",")))

# Make dataframe

data = pd.DataFrame(dummy)
test = pd.DataFrame(dum)

SVM

In [ ]:
# data reduction
np.random.seed(143)
X_train, X_test, y_train, y_test = train_test_split(data, y.labels, test_size=0.1)

In [ ]:
# grid search to check best parameters

parameters = {'gamma' : (0.01, 0.0001, 0.1, 1.0, 10, 'scale', 'auto'), 'C' : (0.0001, 0.001, 0.01, 0.1, 1.0, 10, 100, 1000), 'kernel' : ('rbf', 'poly', 'sigmoid')}

svc = SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(data, y.labels)

clf.best_params_

In [ ]:
# train model using

model = SVC(C=10)

model.fit(X_train, y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
# check accuracy of model only for trial

pred_svm = model.predict(X_test)

print(confusion_matrix(y_test,pred_svm))
print(classification_report(y_test,pred_svm))

[[23  0  0  0  0  0  0  0]
 [ 0 29  0  0  0  0  0  0]
 [ 0  0 23  1  1  1  0  0]
 [ 2  0  2 15  0  4  0  1]
 [ 0  0  0  0 27  0  0  0]
 [ 2  0  0  2  0 16  0  2]
 [ 1  0  0  0  0  1 20  0]
 [ 0  0  0  0  1  0  0 26]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90        23
           1       1.00      1.00      1.00        29
           2       0.92      0.88      0.90        26
           3       0.83      0.62      0.71        24
           4       0.93      1.00      0.96        27
           5       0.73      0.73      0.73        22
           6       1.00      0.91      0.95        22
           7       0.90      0.96      0.93        27

    accuracy                           0.90       200
   macro avg       0.89      0.89      0.89       200
weighted avg       0.90      0.90      0.89       200



In [ ]:
#save data in csv format

pred_svm = model.predict(test)

df = pd.DataFrame(pred_svm)
df.insert(0, 'index', range(df.shape[0]), True)
df.rename(columns={0: "labels"}, inplace=True)
df.reset_index()
# saving the dataframe
df.to_csv('B20ME055_svm_final2.csv', index=False)

K-NN

In [ ]:
knn = KNeighborsClassifier()

parameters = {'n_neighbors' : (1, 3, 5, 7, 9, 11, 13, 15, 17, 18, 19, 20), 'weights' : ('uniform', 'distance'), 'algorithm' : ('auto', 'ball_tree', 'kd_tree', 'brute')}

clf = GridSearchCV(knn, parameters)
clf.fit(data, y.labels)

clf.best_params_

In [ ]:
# knn at value of neighbours = 1

X_train, X_test, y_train, y_test = train_test_split(data, y.labels, test_size=0.30)

knn = KNeighborsClassifier(n_neighbors=1, algorithm='auto', weights='uniform')

knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
pred_knn = knn.predict(X_test)
print(classification_report(y_test,pred_knn))

              precision    recall  f1-score   support

           0       0.88      0.62      0.73        74
           1       0.47      1.00      0.64        61
           2       0.72      0.54      0.62        76
           3       0.73      0.67      0.70        79
           4       0.76      0.80      0.78        74
           5       0.74      0.41      0.53        82
           6       0.74      0.77      0.76        75
           7       0.79      0.87      0.83        79

    accuracy                           0.70       600
   macro avg       0.73      0.71      0.70       600
weighted avg       0.74      0.70      0.70       600



In [ ]:
pred_knn = model.predict(test)

df = pd.DataFrame(pred_knn)

# saving the dataframe1
df.to_csv('B20ME055_knn.csv')

Decision Tree

In [ ]:
dtree_model = DecisionTreeClassifier()

parameters = {'max_depth' : (1, 3, 5, 7, 9, 11, 13, 15, 17, 18, 19, 20),'criterion' : ('entropy', 'gini')}

clf = GridSearchCV(dtree_model, parameters)
clf.fit(data, y.labels)

clf.best_params_

{'criterion': 'gini', 'max_depth': 7}

In [ ]:
# decision tree

dtree_model = DecisionTreeClassifier(max_depth = 7).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)

In [ ]:
print(classification_report(y_test,dtree_predictions))

              precision    recall  f1-score   support

           0       0.56      0.45      0.50        74
           1       0.77      0.80      0.78        61
           2       0.68      0.66      0.67        76
           3       0.42      0.62      0.50        79
           4       0.94      0.78      0.85        74
           5       0.54      0.41      0.47        82
           6       0.66      0.69      0.68        75
           7       0.75      0.78      0.77        79

    accuracy                           0.65       600
   macro avg       0.66      0.65      0.65       600
weighted avg       0.66      0.65      0.65       600



Multinomial Logistic Regression

In [ ]:
# To scale data

# less accuracy when model is trained using scaled data

scaler = StandardScaler()
scaler.fit(data)
dataScaled = scaler.transform(data)

In [ ]:
model = LogisticRegression(multi_class='multinomial')

X_train, X_test, y_train, y_test = train_test_split(dataScaled, y.labels, test_size=0.30)

model.fit(X_train, y_train)
pred = model.predict(X_test)

print(classification_report(y_test,pred))